"""Initial migration

Revision ID: 185567a8c097
Revises: cbf4c48f595a
Create Date: 2026-03-16 14:58:14.783007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185567a8c097'
down_revision: Union[str, Sequence[str], None] = 'cbf4c48f595a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='updated time'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_comments_author_id'), 'incident_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_incident_comments_incident_id'), 'incident_comments', ['incident_id'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('type_', sa.Enum('COMMENT', 'STATUS_CHANGED', 'ASSIGNED', 'CREATED', name='incident_event_type'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='updated time'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_actor_id'), 'incident_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_table('incident_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'DONE', 'CANCELED', name='task_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='updated time'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_tasks_assignee_id'), 'incident_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_incident_tasks_creator_id'), 'incident_tasks', ['creator_id'], unique=False)
    op.create_index(op.f('ix_incident_tasks_incident_id'), 'incident_tasks', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_tasks_incident_id'), table_name='incident_tasks')
    op.drop_index(op.f('ix_incident_tasks_creator_id'), table_name='incident_tasks')
    op.drop_index(op.f('ix_incident_tasks_assignee_id'), table_name='incident_tasks')
    op.drop_table('incident_tasks')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_actor_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_incident_comments_incident_id'), table_name='incident_comments')
    op.drop_index(op.f('ix_incident_comments_author_id'), table_name='incident_comments')
    op.drop_table('incident_comments')
    # ### end Alembic commands ###
