"""Initial migration

Revision ID: cbf4c48f595a
Revises: b34e919c3afb
Create Date: 2026-03-15 17:16:10.140178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbf4c48f595a'
down_revision: Union[str, Sequence[str], None] = 'b34e919c3afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('updated_at', sa.DateTime(), nullable=False, comment='updated time'))
    op.drop_column('incidents', 'updated_time')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, comment='updated time'))
    op.drop_column('users', 'updated_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='updated time'))
    op.drop_column('users', 'updated_at')
    op.add_column('incidents', sa.Column('updated_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='updated time'))
    op.drop_column('incidents', 'updated_at')
    # ### end Alembic commands ###
